"""
Knowledge-layer tables for the LLM-Wiki / OKF architecture.

The compiled knowledge itself lives in the knowledge store as Markdown
(see `app/services/knowledge_store.py`). These tables are the *index* over
it: a derived, fully rebuildable projection that makes the store searchable
and joinable to project ownership.

That split is deliberate. The Markdown pages are the portable artefact you
can copy to S3, read by hand, or diff in git; Postgres holds only what a
query needs — full-text vectors, scope keys, and provenance. Losing the
index costs a reindex, not the knowledge.

`KnowledgeEntry.entry_key` is deterministic (`{paper_id}::{kind}::{ordinal}`)
so recompiling a paper replaces its rows rather than accumulating them —
the same property the old `{paper_id}_chunk_{i}` chunk IDs had, and what
lets citations stay stable across a re-ingest.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    Boolean,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.paper import Paper


#: Entry kinds. `source` is verbatim text lifted from the PDF and is the only
#: kind that may be cited as primary evidence; everything else is compiled and
#: carries provenance back to `source` entries.
KIND_SOURCE = "source"
KIND_COMPILED = "compiled"
KIND_CONCEPT = "concept"
KIND_METHOD = "method"
KIND_TOPIC = "topic"

ENTRY_KINDS = (KIND_SOURCE, KIND_COMPILED, KIND_CONCEPT, KIND_METHOD, KIND_TOPIC)


class KnowledgeEntry(Base):
    """One retrievable unit of knowledge: a paper section, or a compiled page."""

    __tablename__ = "knowledge_entries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )

    #: Stable, deterministic identifier. This is what a citation points at, and
    #: what the chat API still calls `chunk_id` for wire compatibility.
    entry_key: Mapped[str] = mapped_column(String(255), nullable=False)

    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    #: Canonical slug for concept/method/topic entries; NULL for paper content.
    slug: Mapped[str | None] = mapped_column(String(255), nullable=True)

    title: Mapped[str | None] = mapped_column(String(512), nullable=True)
    #: Detected section heading ("Methodology", "Results", ...).
    section: Mapped[str | None] = mapped_column(String(255), nullable=True)
    body: Mapped[str] = mapped_column(Text, nullable=False)

    page: Mapped[int | None] = mapped_column(Integer, nullable=True)
    #: Order within the paper. Preserved so evidence can be presented in
    #: document order and so `entry_key` is reproducible.
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    #: {source_file, page, section, source_text, evidence_keys[]}
    provenance: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    #: Generated by Postgres — see the migration. Declaring the Computed() here
    #: too is what stops SQLAlchemy emitting the column in INSERT/UPDATE.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('english', coalesce(title, '')), 'A') || "
            "setweight(to_tsvector('english', coalesce(section, '')), 'B') || "
            "setweight(to_tsvector('english', coalesce(body, '')), 'C')",
            persisted=True,
        ),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    paper: Mapped["Paper"] = relationship()

    __table_args__ = (
        UniqueConstraint("entry_key", name="uq_knowledge_entries_entry_key"),
        Index("ix_knowledge_entries_paper_id", "paper_id"),
        Index("ix_knowledge_entries_kind", "kind"),
        Index("ix_knowledge_entries_slug", "slug"),
        # The retrieval index. GIN over the generated tsvector.
        Index(
            "ix_knowledge_entries_search",
            "search_vector",
            postgresql_using="gin",
        ),
    )

    def __repr__(self) -> str:
        return f"<KnowledgeEntry {self.entry_key} kind={self.kind}>"


class PaperConcept(Base):
    """A concept/method/topic asserted by one paper, with its evidence.

    Shared identity lives in `concept_key`: two papers discussing the same
    canonical concept produce two rows with the same key, which is what makes
    the concept graph a graph. This mirrors the old Neo4j model (shared
    `:Concept` nodes, per-paper `HAS_CONCEPT` edges) without a graph database.
    """

    __tablename__ = "paper_concepts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )

    #: Canonicalized key, produced by `concept_service.canonical_key`.
    concept_key: Mapped[str] = mapped_column(String(255), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    kind: Mapped[str] = mapped_column(String(32), nullable=False, default=KIND_CONCEPT)

    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Pages the evidence quote was located on.
    pages: Mapped[list[Any] | None] = mapped_column(JSONB, nullable=True)
    #: `KnowledgeEntry.entry_key` values the evidence was located in.
    entry_keys: Mapped[list[Any] | None] = mapped_column(JSONB, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    paper: Mapped["Paper"] = relationship()

    __table_args__ = (
        UniqueConstraint("paper_id", "concept_key", name="uq_paper_concepts_paper_key"),
        Index("ix_paper_concepts_paper_id", "paper_id"),
        Index("ix_paper_concepts_concept_key", "concept_key"),
    )

    def __repr__(self) -> str:
        return f"<PaperConcept {self.concept_key} paper={self.paper_id}>"


class ConceptRelation(Base):
    """A concept-to-concept edge asserted by one paper.

    Scoped to the asserting paper so re-ingesting that paper can replace its
    own claims without touching another paper's.
    """

    __tablename__ = "concept_relations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    source_key: Mapped[str] = mapped_column(String(255), nullable=False)
    target_key: Mapped[str] = mapped_column(String(255), nullable=False)
    relation_type: Mapped[str] = mapped_column(String(64), nullable=False, default="RELATES_TO")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        UniqueConstraint(
            "paper_id", "source_key", "target_key", "relation_type",
            name="uq_concept_relations_edge",
        ),
        Index("ix_concept_relations_paper_id", "paper_id"),
    )

    def __repr__(self) -> str:
        return f"<ConceptRelation {self.source_key}->{self.target_key}>"


class PaperCitation(Base):
    """A citation edge between a local paper and another work.

    The other end is usually *not* in `papers` — the old pipeline deliberately
    refused to insert unverified external works into PostgreSQL, and that
    decision is preserved. Its metadata is therefore denormalized here.

    `direction` is from the local paper's point of view:
      * `outbound` — this paper cites the other work (a reference)
      * `inbound`  — the other work cites this paper (a citation)
    """

    __tablename__ = "paper_citations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    direction: Mapped[str] = mapped_column(String(16), nullable=False)

    #: Deterministic UUID5 for an external work, or a real `papers.id`.
    other_id: Mapped[str] = mapped_column(String(64), nullable=False)
    other_title: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    other_year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    other_doi: Mapped[str | None] = mapped_column(String(255), nullable=True)
    other_arxiv_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    other_semantic_scholar_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    other_has_pdf: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        UniqueConstraint("paper_id", "direction", "other_id", name="uq_paper_citations_edge"),
        Index("ix_paper_citations_paper_id", "paper_id"),
    )

    def __repr__(self) -> str:
        return f"<PaperCitation {self.paper_id} {self.direction} {self.other_id}>"
