"""Add UserHistory model

Revision ID: 0ff8a78aba04
Revises: a161da9310c7
Create Date: 2026-08-25 00:48:09.628139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ff8a78aba04'
down_revision: Union[str, Sequence[str], None] = 'a161da9310c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_history_created_at'), 'user_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_history_event_type'), 'user_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_history_id'), 'user_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_history_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_event_type'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_created_at'), table_name='user_history')
    op.drop_table('user_history')
    # ### end Alembic commands ###
