"""Add project and paper models

Revision ID: 16ad66ff7efc
Revises: ffffcae62153
Create Date: 2026-08-17 06:30:19.476333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16ad66ff7efc'
down_revision: Union[str, Sequence[str], None] = 'ffffcae62153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('doi', sa.String(length=255), nullable=True))
    op.add_column('papers', sa.Column('arxiv_id', sa.String(length=255), nullable=True))
    op.add_column('papers', sa.Column('semantic_scholar_id', sa.String(length=255), nullable=True))
    op.add_column('papers', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('reference_count', sa.Integer(), nullable=True))
    op.alter_column('papers', 'title',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('papers', 'venue',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('papers', 'pdf_url',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('papers', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('papers', 'citation_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_papers_owner_id'), table_name='papers')
    op.create_unique_constraint(None, 'papers', ['arxiv_id'])
    op.create_unique_constraint(None, 'papers', ['doi'])
    op.create_unique_constraint(None, 'papers', ['semantic_scholar_id'])
    op.drop_constraint(op.f('papers_owner_id_fkey'), 'papers', type_='foreignkey')
    op.drop_column('papers', 'priority')
    op.drop_column('papers', 'year')
    op.drop_column('papers', 'reading_status')
    op.drop_column('papers', 'updated_at')
    op.drop_column('papers', 'tags')
    op.drop_column('papers', 'is_favorite')
    op.drop_column('papers', 'authors')
    op.drop_column('papers', 'owner_id')
    op.add_column('project_papers', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('project_papers', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('project_papers', sa.Column('favorite', sa.Boolean(), nullable=False))
    op.add_column('project_papers', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('projects', 'color',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.alter_column('projects', 'color',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('projects', 'user_id')
    op.drop_column('project_papers', 'priority')
    op.drop_column('project_papers', 'favorite')
    op.drop_column('project_papers', 'status')
    op.drop_column('project_papers', 'id')
    op.add_column('papers', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('papers', sa.Column('authors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('papers', sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('papers', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('papers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('papers', sa.Column('reading_status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('papers', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('papers', sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('papers_owner_id_fkey'), 'papers', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'papers', type_='unique')
    op.drop_constraint(None, 'papers', type_='unique')
    op.drop_constraint(None, 'papers', type_='unique')
    op.create_index(op.f('ix_papers_owner_id'), 'papers', ['owner_id'], unique=False)
    op.alter_column('papers', 'citation_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('papers', 'source',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('papers', 'pdf_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('papers', 'venue',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('papers', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('papers', 'reference_count')
    op.drop_column('papers', 'publication_year')
    op.drop_column('papers', 'semantic_scholar_id')
    op.drop_column('papers', 'arxiv_id')
    op.drop_column('papers', 'doi')
    # ### end Alembic commands ###
