"""Add Collections

Revision ID: c8e966ebc172
Revises: ff475dcd998e
Create Date: 2026-08-23 22:34:54.269406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e966ebc172'
down_revision: Union[str, Sequence[str], None] = 'ff475dcd998e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('summary_eli5', sa.Text(), nullable=True),
    sa.Column('summary_student', sa.Text(), nullable=True),
    sa.Column('summary_researcher', sa.Text(), nullable=True),
    sa.Column('should_read', sa.Text(), nullable=True),
    sa.Column('novelty', sa.Text(), nullable=True),
    sa.Column('research_gap', sa.Text(), nullable=True),
    sa.Column('datasets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('algorithms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('future_work', sa.Text(), nullable=True),
    sa.Column('glossary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id')
    )
    op.create_table('collection_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_project_papers_paper_id'), table_name='project_papers')
    op.drop_index(op.f('ix_project_papers_project_id'), table_name='project_papers')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_papers_project_id'), 'project_papers', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_papers_paper_id'), 'project_papers', ['paper_id'], unique=False)
    op.drop_table('collection_papers')
    op.drop_table('paper_analyses')
    op.drop_table('collections')
    # ### end Alembic commands ###
